#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards
npm run check-format || (
  echo '❌ Prettier Check Failed.'
  false;
)
echo '✅ Prettier Check success.'

# Check ESLint Standards
npm run check-lint || (
  echo '❌ ESLint Check Failed.'
  false;
)
echo '✅ ESLint Check success.'

# Check tsconfig standards
npm run check-types || (
  echo '❌ Type check Failed.'
  false;
)
echo '✅ Type check success.'

echo '*️⃣ Build in process...'

npm run build || (
  echo '❌ Next build Failed.'
  false;
)

echo '✅ Build is done.'